Figure out what's up with GITHUB_BRANCH
I think this variable is missing. Toward #776

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -89,11 +89,15 @@ jobs:
           
       - name: Configure deployment type
         run: |
+          echo GitHub branch is "$GITHUB_BRANCH"
           if [ "$GITHUB_BRANCH" = "master" ]; then
             ./deploy/increase_verbosity.sh
             cp appspec-staging.yml appspec.yml
           elif [ "$GITHUB_BRANCH" = "deploy" ]; then
             cp appspec-deploy.yml appspec.yml
+          else
+            echo "Error: Deployment can only be run from 'master' or 'deploy' branches."
+            exit 1
           fi
           
       - name: Upload artifact
